[package]
name = "lovely-android"
version = "0.1.0"
edition = "2021"

[lib]
name = "lovely"
crate-type = ["lib", "cdylib"]

[dependencies]
lovely-core = { version ="0.7.1", path = "../lovely-core" }

jni = "0.5.2"
once_cell = "1.19.0"
ctor = "0.2.7"
android_log = "0.1.3"
log = "0.4.26"
